### PR TITLE
Updated AM2

### PR DESCRIPTION
**Pull request by TheIcyOne**
Fixes the bug mentioned in private report.

### CODE REVIEW

**Comment by Bennyboy1695** [comment]
There's one issue with this commit, curse and ftb will never allow this pack to be updated while it contains this. This is because its technically a new mod due to ars magica being updated last in February and this having all ars magica code plus custom editions. You'll either need to keep it off the other launchers if this is kept or obtain proper permission to update the mod or create a complete custom version yourselfs

**Comment by johnfg2610** [comment]
its a open source mod so this should be allowed
https://creativecommons.org/licenses/by-nc/3.0/legalcode

"You are free to:

Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following conditions:

Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
NonCommercial — You may not use the material for commercial purposes.
No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits."

**Comment by Bennyboy1695** [comment]
Open source mods are usually open source so that you can learn from their code and/or create mods using an api, or create pull requests containing fixes. Curse may allow you to use it but im very doubtful

**Comment by johnfg2610** [comment]
we have been using it for a while ? so should be ok

**Comment by Bennyboy1695** [comment]
On the mym launcher is fine as long as nobody notices its an unofficial version, but i've just seen curse and ftb dont have the latest updates so if its know just mym launcher you'll probably have no issues. This was just a warning as i though you guys still used curse

**Comment by johnfg2610** [comment]
i though we did ... 

if its not allowed il remove it but as far as i can see its fine not sure though licences arnt my strong point

**Comment by Bennyboy1695** [comment]
well unless im being blind im not seeing ars in the curse version :stuck_out_tongue:

**Comment by johnfg2610** [comment]
who would i talk to at curse about this ?

**Comment by Bennyboy1695** [comment]
no idea, i know slind is a collaborator on the pack on curse, so he may know

**Comment by johnfg2610** [comment]
what version are u looking at?

**Comment by Bennyboy1695** [comment]
Had to download it actually on curse to see that it is in there. Just isnt listed in the mod list in the description and doesnt have ars magica as one of its relations which was why i couldnt see it

**Comment by johnfg2610** [comment]
so its good?

**Comment by johnfg2610** [comment]
image

i can see it ;

**Comment by Bennyboy1695** [comment]
Appears to be.
I did look at the licesne of the mod and i was right your not allowed custom versions when they are made public (ie. a public modpack)

From the license on the github :/  "NonCommercial — You may not use the material for commercial purposes."

**Comment by johnfg2610** [comment]
this is commercial? not making money out of it

**Comment by Bennyboy1695** [comment]
Commercial doesnt always mean making money from something, but the dude isn't very descriptive an his license :( He could mean multiple different things. The way it reads to me though is your allowed to use custom versions as long as they arent made public. i may be reading it wrong though so i'll leave you guys too it, do have to say though, your a brave one to attempt to fix am2 icy :stuck_out_tongue_winking_eye:

**Comment by johnfg2610** [comment]
@TheIcyOne @Sir-Will @Slind14 im not sure i was of the understanding this was ok (more then possibly wrong :P ) anyhow could we have input plz :)

**Comment by bookerthegeek** [comment]
- link to location you acquired the mod file
- link to terms and conditions

Worst case I'll ask the devs of ars2 tonight.

**Comment by johnfg2610** [comment]
heres icys version (hopes its upto date) https://github.com/TheIcyOne/ArsMagica2
and the licences seems to be unchanged

**Comment by TheIcyOne** [comment]
Not currently up to date, I can dump the changes on there if needed.

**Comment by TheIcyOne** [comment]
Just to note, the changes in the current version on Civ are part of a pull request to the official AM2, the one in that update are for MyM only, as they would be a little heavy-handed for an AM2 only setup, by preventing hecates attacking iron and snow golems as originally intended.

**Comment by TheIcyOne** [comment]
Also, the terms mentioned in the license apply to sharing as well @Bennyboy1695

**Comment by johnfg2610** [comment]
me and @TheIcyOne were talking and surely selling the kit is commercial? (once again could be wrong) which would mean the licence is being broke on the server? 

good chance i just dont get them meaning of commercial but still

**Comment by TheIcyOne** [comment]
https://creativecommons.org/licenses/by-nc/3.0/

Simpler form.

**Comment by johnfg2610** [comment]
"A commercial use is one primarily intended for commercial advantage or monetary compensation."
"Adapt — remix, "
so its allowed?

**Comment by bookerthegeek** [comment]
I'm looking into it, I'll have an answer for you tonight

**Comment by johnfg2610** [comment]
ok thanks :) (im terrible at this stuff)

**Comment by bookerthegeek** [comment]
Please make a pull request with the Ars Magica github for the fix.

Redistribution of the files is not allowed per devs of ars magica. This needs to be un-merged.

**Pull request merged**
